### ISSUE TITLE
[Question] How do you insert data into a gtk.ListStore?

### ISSUE THREAD

**Issue by shackra** [conformal/gotk3#102]
I was wondering this as the `gtk.ListStore.Append` method expression do not receive parameters.

**Comment by jrick** [comment]
You need to call `(*gtk.ListStore).Set(treeIter, ...)` ([doco here](http://godoc.org/github.com/conformal/gotk3/gtk#ListStore.Set)) with the `treeIter` returned by `Append`.  It's a little wonky but matches the C API.

**Comment by elzorrorebelde** [comment]
I see... How do I set the data in that `gtk.TreeIter` struct?

**Comment by elzorrorebelde** [comment]
Ohh... I see. Thanks for the clarification!
