### ISSUE TITLE
Less Convoluted Windows Install

### ISSUE THREAD

**Issue by Immortalin** [conformal/gotk3#104]
Hi,

Instead of the convoluted windows install method as detailed in the wiki, why can't you use the [standard gtk windows installation method](http://www.gtk.org/download/win32.php)?

**Comment by jrick** [comment]
I was aware of that installation process but it used (and still uses) a very old GTK version, which wasn't even supported by gotk3 when I wrote the instructions (gotk3 began as 3.8+ only).  The new instructions detail how to get a reasonably new GTK on windows, and should work for any GTK version that you can find fedora mingw-w64 packages for.
