### ISSUE TITLE
Is this project a dead one?

### ISSUE THREAD

**Issue by russel** [conformal/gotk3#117]
It looks like this repository hasn't been updated in a year or more, yet there is activity in terms of issues and pull requests.

Should this project for forked to an active one that keeps up with GTK3 developments?

**Comment by jrick** [comment]
Development continues over at https://github.com/gotk3/gotk3 but it's no longer being developed by Conformal.

**Comment by russel** [comment]
Aha, already forked. I had missed that. Thanks for letting me know. Appropriate action now being taken. :-)
