### ISSUE TITLE
Inheritance

### ISSUE THREAD

**Issue by raichu** [conformal/gotk3#13]
This is more like a question but, how do we access functions of a "parent class"? For example, how can I call `SetVisible` (of Widget) method for a `ScrolledWindow` object?

As far I understand, there is no concept of inheritance (or struct embedding) at the moment. Is this correct?
Is the correct way of doing this to use the Widget field?

**Comment by jrick** [comment]
We are using struct embedding, so this will work.  ScrolledWindow embeds a Bin, Bin embeds Container, and Container embeds Widget.  Just call sw.SetVisible(setting).

**Comment by raichu** [comment]
Thanks! Found out a bit late :)
