### ISSUE TITLE
Question: Can't install

### ISSUE THREAD

**Issue by krolaw** [conformal/gotk3#25]
$ go get github.com/conformal/gotk3/gtk
# github.com/conformal/gotk3/gtk

37: error: 'gtk_window_close' undeclared (first use in this function)

Running Ubuntu 13.10.  Wondering if this is a bug or I'm missing packages.

http://en.wikipedia.org/wiki/Gtk  C code example compiles fine.

Thanks.

**Comment by jrick** [comment]
You'll need to use build tags to target a previous GTK version.  This is documented in the README.  Try rebuilding with:

go get -tags gtk_3_8 github.com/conformal/gotk3/gtk
