### ISSUE TITLE
TextTagTable Causes Runtime Error

### ISSUE THREAD

**Issue by dahenson** [conformal/gotk3#40]
Using [TextTagTableNew()](https://github.com/conformal/gotk3/blob/master/gtk/gtk.go#L4105) creates a runtime error because the function invokes [gtk_tree_view_new()](https://github.com/conformal/gotk3/blob/master/gtk/gtk.go#L4106).

I apologize for not just submitting a pull request, but I'm not in a place where I can do anything about it yet. I just wanted to throw this issue out there to earmark it for fixing. I'll try to submit a pull request sometime this weekend.

**Comment by jrick** [comment]
Oops, sorry about that. Fixing now.
