### ISSUE TITLE
I got a error, when i install gotk3

### ISSUE THREAD

**Issue by KORedFish** [conformal/gotk3#46]
// go version go1.0.3

$ sudo go get github.com/conformal/gotk3/gtk

i typing this command ... 

and ..

get a this message...

[ # github.com/conformal/gotk3/glib
glib.go:283[/tmp/go-build733895966/github.com/conformal/gotk3/glib/_obj/glib.cgo1.go:269]: rv.Convert undefined (type reflect.Value has no field or method Convert)
glib.go:292[/tmp/go-build733895966/github.com/conformal/gotk3/glib/_obj/glib.cgo1.go:277]: rv.Convert undefined (type reflect.Value has no field or method Convert) ]

what's the problem with me?

**Comment by davecgh** [comment]
@KORedFish: Your Go version it too old.  Gotk3 requires Go version 1.2 as Convert wasn't introduced to the standard library reflect package until later versions.

@jrick: Can you please add the required Go version to the README / Install instructions?
