### ISSUE TITLE
Error while building btcgui / gotk3

### ISSUE THREAD

**Issue by kawalgrover** [conformal/gotk3#49]
$ go version
go version go1.2 linux/amd64

$ go get -u -v github.com/conformal/btcgui/...

github.com/conformal/btcgui (download)
code.google.com/p/go.crypto (download)
code.google.com/p/go.net (download)
github.com/conformal/btcdb (download)
github.com/conformal/btcec (download)
github.com/conformal/btclog (download)
github.com/conformal/seelog (download)
github.com/conformal/btcutil (download)
github.com/conformal/btcwire (download)
github.com/conformal/fastsha256 (download)
github.com/conformal/btcjson (download)
github.com/conformal/btcws (download)
github.com/conformal/go-flags (download)
github.com/conformal/go-socks (download)
github.com/conformal/gotk3 (download)
github.com/conformal/gotk3/gdk
github.com/conformal/gotk3/gtk
# github.com/conformal/gotk3/gtk

37: error: 'gtk_list_box_set_selection_mode' undeclared (first use in this function)
37: error: 'gtk_stack_add_named' undeclared (first use in this function)
37: error: 'GTK_STACK_TRANSITION_TYPE_SLIDE_UP_DOWN' undeclared (first use in this function)
37: error: 'gtk_revealer_set_transition_type' undeclared (first use in this function)
37: error: 'gtk_search_bar_set_show_close_button' undeclared (first use in this function)
37: error: 'gtk_stack_switcher_get_stack' undeclared (first use in this function)
37: error: 'gtk_revealer_set_reveal_child' undeclared (first use in this function)
38: error: 'gtk_stack_set_transition_type' undeclared (first use in this function)
38: error: 'gtk_list_box_prepend' undeclared (first use in this function)
38: error: 'gtk_list_box_row_get_header' undeclared (first use in this function)
38: error: 'gtk_stack_get_visible_child_name' undeclared (first use in this function)
38: error: 'gtk_window_set_titlebar' undeclared (first use in this function)
38: error: 'GTK_STACK_TRANSITION_TYPE_SLIDE_DOWN' undeclared (first use in this function)
38: error: 'gtk_list_box_set_adjustment' undeclared (first use in this function)
38: error: 'gtk_stack_get_visible_child' undeclared (first use in this function)
38: error: 'gtk_list_box_get_row_at_y' undeclared (first use in this function)
38: error: 'gtk_list_box_row_changed' undeclared (first use in this function)
38: error: 'gtk_revealer_get_transition_type' undeclared (first use in this function)
38: error: 'gtk_stack_switcher_set_stack' undeclared (first use in this function)
38: error: 'GTK_REVEALER_TRANSITION_TYPE_SLIDE_DOWN' undeclared (first use in this function)
38: error: 'gtk_list_box_drag_highlight_row' undeclared (first use in this function)
38: error: 'gtk_stack_add_titled' undeclared (first use in this function)
38: error: 'gtk_stack_get_homogeneous' undeclared (first use in this function)
38: error: 'gtk_header_bar_set_show_close_button' undeclared (first use in this function)
38: error: 'gtk_list_box_get_selection_mode' undeclared (first use in this function)
38: error: 'gtk_list_box_get_row_at_index' undeclared (first use in this function)
38: error: 'gtk_list_box_invalidate_headers' undeclared (first use in this function)
38: error: 'GtkRevealerTransitionType' undeclared (first use in this function)
38: error: 'gtk_stack_set_visible_child_full' undeclared (first use in this function)
38: error: 'gtk_stack_get_transition_duration' undeclared (first use in this function)
38: error: 'GTK_STACK_TRANSITION_TYPE_NONE' undeclared (first use in this function)
38: error: 'gtk_stack_set_transition_duration' undeclared (first use in this function)
38: error: 'GTK_REVEALER_TRANSITION_TYPE_SLIDE_LEFT' undeclared (first use in this function)
38: error: 'gtk_label_get_lines' undeclared (first use in this function)
38: error: 'GtkListBoxRow' undeclared (first use in this function)
38: error: 'gtk_header_bar_set_custom_title' undeclared (first use in this function)
38: error: 'gtk_revealer_get_transition_duration' undeclared (first use in this function)
38: error: 'gtk_list_box_new' undeclared (first use in this function)
38: error: 'gtk_revealer_get_child_revealed' undeclared (first use in this function)
38: error: 'gtk_search_bar_connect_entry' undeclared (first use in this function)
38: error: 'gtk_stack_set_visible_child_name' undeclared (first use in this function)
38: error: 'GTK_STACK_TRANSITION_TYPE_CROSSFADE' undeclared (first use in this function)
38: error: 'gtk_header_bar_get_custom_title' undeclared (first use in this function)
38: error: 'gtk_search_bar_new' undeclared (first use in this function)
38: error: 'GTK_REVEALER_TRANSITION_TYPE_SLIDE_RIGHT' undeclared (first use in this function)
38: error: 'gtk_label_set_lines' undeclared (first use in this function)
38: error: 'gtk_list_box_invalidate_filter' undeclared (first use in this function)
38: error: 'GtkRevealer' undeclared (first use in this function)
38: error: 'GTK_STACK_TRANSITION_TYPE_SLIDE_LEFT_RIGHT' undeclared (first use in this function)
38: error: 'gtk_header_bar_set_title' undeclared (first use in this function)
38: error: 'gtk_list_box_select_row' undeclared (first use in this function)
38: error: 'gtk_list_box_invalidate_sort' undeclared (first use in this function)
38: error: 'gtk_list_box_row_get_index' undeclared (first use in this function)
38: error: 'GtkHeaderBar' undeclared (first use in this function)
38: error: 'gtk_header_bar_pack_start' undeclared (first use in this function)
38: error: 'GtkStack' undeclared (first use in this function)
38: error: 'gtk_window_close' undeclared (first use in this function)
38: error: 'gtk_header_bar_set_subtitle' undeclared (first use in this function)
38: error: 'gtk_header_bar_get_subtitle' undeclared (first use in this function)
38: error: 'gtk_list_box_get_selected_row' undeclared (first use in this function)
38: error: 'gtk_list_box_get_activate_on_single_click' undeclared (first use in this function)
38: error: 'gtk_list_box_set_placeholder' undeclared (first use in this function)
38: error: 'gtk_search_bar_get_search_mode' undeclared (first use in this function)
38: error: 'gtk_search_bar_set_search_mode' undeclared (first use in this function)
38: error: 'GTK_ALIGN_BASELINE' undeclared (first use in this function)
38: error: 'GTK_STACK_TRANSITION_TYPE_SLIDE_LEFT' undeclared (first use in this function)
38: error: 'gtk_list_box_get_adjustment' undeclared (first use in this function)
38: error: 'gtk_header_bar_get_title' undeclared (first use in this function)
38: error: 'gtk_list_box_set_activate_on_single_click' undeclared (first use in this function)
38: error: 'gtk_revealer_set_transition_duration' undeclared (first use in this function)
38: error: 'GtkStackSwitcher' undeclared (first use in this function)
38: error: 'GTK_REVEALER_TRANSITION_TYPE_NONE' undeclared (first use in this function)
38: error: 'GTK_REVEALER_TRANSITION_TYPE_SLIDE_UP' undeclared (first use in this function)
38: error: 'gtk_list_box_row_new' undeclared (first use in this function)
38: error: 'gtk_search_bar_handle_event' undeclared (first use in this function)
38: error: 'gtk_stack_set_homogeneous' undeclared (first use in this function)
38: error: 'GtkSearchBar' undeclared (first use in this function)
38: error: 'GTK_STACK_TRANSITION_TYPE_SLIDE_UP' undeclared (first use in this function)
38: error: 'gtk_header_bar_new' undeclared (first use in this function)
38: error: 'gtk_header_bar_get_show_close_button' undeclared (first use in this function)
38: error: 'GtkListBox' undeclared (first use in this function)
38: error: 'GtkStackTransitionType' undeclared (first use in this function)
38: error: 'GTK_REVEALER_TRANSITION_TYPE_CROSSFADE' undeclared (first use in this function)
39: error: 'gtk_list_box_insert' undeclared (first use in this function)
39: error: 'gtk_list_box_row_set_header' undeclared (first use in this function)
39: error: 'gtk_revealer_get_reveal_child' undeclared (first use in this function)
39: error: 'gtk_stack_set_visible_child' undeclared (first use in this function)
39: error: 'gtk_stack_switcher_new' undeclared (first use in this function)
39: error: 'gtk_header_bar_pack_end' undeclared (first use in this function)
39: error: 'gtk_revealer_new' undeclared (first use in this function)
39: error: 'gtk_search_bar_get_show_close_button' undeclared (first use in this function)
39: error: 'gtk_stack_new' undeclared (first use in this function)
39: error: 'GTK_STACK_TRANSITION_TYPE_SLIDE_RIGHT' undeclared (first use in this function)
39: error: 'gtk_stack_get_transition_type' undeclared (first use in this function)

(Note, I got the latest versions of cairo,  glib-2.0  before doing this build ).

Those specific commands are:
sudo apt-get install libcairo2-dev
sudo apt-get install libglib2.0-dev

Let me know if I'm missing anything else. I am fairly new to Ubuntu and Go. :)

Thank you in advance!

**Comment by weberc2** [comment]
You're missing GTK. I'm not sure what version of Ubuntu you're running, but you'll need to run something like `sudo apt-get install libgtk-3-dev` (I can't verify at the moment). Once you have GTK, you'll likely need to build with something like `go build -tags=gtk_3_8 github.com/conformal/btcgui/...` (if you want to install it, swap out 'build' for 'install').

**Comment by jrick** [comment]
No, he does have GTK (because GDK built, GDK is a part of GTK).  It's just the missing tags.  All of those compile errors are for 3.10 features.

**Comment by kawalgrover** [comment]
Correcto Mundo... .I was just missing the tags.

That did it. I really really appreciate your quick response. You guys are awesome!

Thanks again.
