### ISSUE TITLE
gdk.GetPixels returns a copy of the buffer, so it is impossible to set values

### ISSUE THREAD

**Issue by vvanpo** [conformal/gotk3#53]
What is the best way to resolve this?  We can't return the C array directly, but C.GoBytes() automatically produces a copy.  The GDK documentation example (https://developer.gnome.org/gdk-pixbuf/stable/gdk-pixbuf-The-GdkPixbuf-Structure.html#put-pixel) uses the buffer pointer directly to set values, is there a more Go-friendly way to accomplish the same thing?

**Comment by jrick** [comment]
Can you test after applying this patch? That will return a go slice pointing to the internal buffer. http://sprunge.us/GcCI

**Comment by vvanpo** [comment]
Hi jrick, yes that works great.  After my initial comment I actually found that exact solution, but I was a little put off by the warning in the docs (http://godoc.org/reflect#SliceHeader).  I guess we'll have to wait and see if this breaks in future releases.
