### ISSUE TITLE
Bug?

### ISSUE THREAD

**Issue by metalneox** [conformal/gotk3#68]
I have installed gotk3 now but create current error:

github.com/conformal/gotk3/gtk/gtk.go:2518: cannot use &cwlist (type *__Ctype_struct__GList) as type *__Ctype_GList in function argument

I have commented function GetFocusChain and now work.

**Comment by jrick** [comment]
It's a bug with the Go 1.3 compiler (it seems to be a race between setting a C typedef, and looking it up).  Keep rebuilding it and eventually it will work. :(

**Comment by metalneox** [comment]
But im use Go 1.2 compiler over ubuntu 64bit(virtual machine)

**Comment by jrick** [comment]
Hmm that's very odd then.  Did you try rebuilding a couple times? Still doesn't work?

**Comment by metalneox** [comment]
It wasn't working, but now i have commented the function and it works. Don't worry, it's not a critical problem

**Comment by celrenheit** [comment]
Hello,
I am getting the same error when trying to install btcgui:

```
../gotk3/gtk/gtk.go:2517: cannot use &cwlist (type **_Ctype_struct__GList) as type **_Ctype_GList in function argument

```

**Comment by jcvernaleo** [comment]
jrick I get the exact same error and I have tried to build a ton of times.  And this is not with go1.3.

Recent-ish bitrig snap with:
jcv@ryu gtk $  go version
go version go1.2.1 openbsd/amd64

**Comment by jrick** [comment]
Yeah sorry it wasn't a compiler error, I had the wrong type there after all.  Odd that it was able to compile for me (Go 1.3, GTK 3.12).

Fix should be on master, let me know if you run into any other issues.
