### ISSUE TITLE
Error messages when compiling on Ubuntu Trusty

### ISSUE THREAD

**Issue by dmgolubovsky** [conformal/gotk3#81]
Hi,
When compiling any example program, I get the following messages:
# github.com/conformal/gotk3/gtk

37: error: 'gtk_popover_set_relative_to' undeclared (first use in this function)
37: error: 'gtk_popover_get_relative_to' undeclared (first use in this function)
37: error: 'gtk_widget_get_margin_start' undeclared (first use in this function)
37: error: 'gtk_widget_set_margin_start' undeclared (first use in this function)
37: error: 'gtk_popover_get_type' undeclared (first use in this function)
37: error: 'gtk_popover_get_modal' undeclared (first use in this function)
38: error: 'gtk_widget_get_margin_end' undeclared (first use in this function)
38: error: 'gtk_widget_set_margin_end' undeclared (first use in this function)
38: error: 'gtk_popover_new' undeclared (first use in this function)
38: error: 'gtk_popover_set_modal' undeclared (first use in this function)
38: error: 'GtkPopover' undeclared (first use in this function)
38: error: 'gtk_popover_set_position' undeclared (first use in this function)
38: error: 'gtk_popover_get_position' undeclared (first use in this function)

however the executable builds and works.

From time to time (randomly) I may see the following messages:
# github.com/conformal/gotk3/gtk

../github.com/conformal/gotk3/gtk/gtk.go:2528: cannot use &cwlist (type *_C.struct__GList) as type *_C.GList in argument to _Cfunc_gtk_container_get_focus_chain
../github.com/conformal/gotk3/gtk/gtk.go:2550: cannot use glist (type _C.struct__GList) as type *C.GList in argument to _Cfunc_gtk_container_set_focus_chain
../github.com/conformal/gotk3/gtk/gtk.go:7708: cannot use (_C.struct__GList)(unsafe.Pointer(glist)) (type *C.struct__GList) as type *C.GList in argument to _Cfunc_g_list_free_full

shell returned 2

and the executable does not build. No changes in the program, just randomly.

System description:

uname -a
Linux hpcompaq 3.13.0-35-generic #62-Ubuntu SMP Fri Aug 15 01:58:42 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux
go version go1.3 linux/amd64
gcc --version
gcc (Ubuntu 4.8.2-19ubuntu1) 4.8.2
pkg-config --modversion gtk+-3.0 
3.10.8

build command:
go build -tags gtk_3_10 -ldflags -s

Thanks.

**Comment by jrick** [comment]
Updating to Go 1.3.1 should resolve the problem.  Unfortunately, Go 1.3 shipped with a broken cgo which caused issues compiling not just gotk3, but other Go packages that interface with C.

**Comment by dmgolubovsky** [comment]
Thanks.
I upgraded to go 1.3.1. Messages of the first type (37: error: 'gtk_popover_set_relative_to' undeclared (first use in this function) etc.) still there, but messages of the second type (which caused build failure) seem to be gone. Just commenting, not insisting to reopen the bug.

**Comment by jrick** [comment]
GtkPopover is a 3.12 feature.  I saw from your original post that you (correctly, I assume) used the gtk_3_10 build tag.  Did you forget it this time?

edit: oh sorry, you saw those errors _with_ the 3.10 build tag before?

**Comment by dmgolubovsky** [comment]
The flag gtk_3_10 is still there, and I saw these messages before with this flag set. Without this flag I could not (obviously) build any of the test executables at all. Which now really surprises me because
grep -ilr popover src/github.com/conformal/
src/github.com/conformal/gotk3/gtk/gtk_3_12.go.h
src/github.com/conformal/gotk3/gtk/gtk_3_12.go

that is popover is only present in the 3.12 version.

but as long as I can build executables with this I can live with this.

Thanks.

**Comment by Somesh-zz** [comment]
Getting same error,

uname -a
Linux dawslmktbeta01 3.13.0-52-generic #86-Ubuntu SMP Mon May 4 04:32:59 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

go version go1.3.3 linux/amd64 .(Since I have 1.3.3, hence assuming that the issue reported about 1.3 should be resolved.)
gcc (Ubuntu 4.8.2-19ubuntu1) 4.8.2

Any suggestions ?

Thanks
