### ISSUE TITLE
Where to go after designing your app UI with Glade?

### ISSUE THREAD

**Issue by shackra** [conformal/gotk3#99]
I have experience with GUI applications done with PySide (Qt bindings for Python). But with these bindings I have no idea what should I do after designing the application's interface with Glade.

**Comment by weberc2** [comment]
Load the glade file with a gtk.Builder. check out its API for more info.

**Comment by elzorrorebelde** [comment]
Oh, I see!

Thank you!

weberc2 writes:

> Load the glade file with a gtk.Builder. check out its API for more info.
> On Jan 1, 2015 2:16 PM, "Jorge Araya Navarro" notifications@github.com
> wrote:
> 
> > I have experience with GUI applications done with PySide (Qt bindings for
> > Python). But with these bindings I have no idea what should I do after
> > designing the application's interface with Glade.
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > https://github.com/conformal/gotk3/issues/99.
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/conformal/gotk3/issues/99#issuecomment-68497110

## 

Pax et bonum.
Jorge Araya Navarro.
ES: Diseñador Publicitario, Programador Python y colaborador en Parabola GNU/Linux-libre
EN: Ads Designer, Python programmer and contributor Parabola GNU/Linux-libre
EO: Anonco grafikisto, Pitino programalingvo programisto kai kontribuanto en Parabola GNU/Linux-libre
https://es.gravatar.com/shackra
